global.TrainingView = (function() {

  let $mainCategories;
  let $partCategories;

  function init() {
    $mainCategories = {};
    $partCategories = {};

    SexAction.getAllCodes().forEach(code => {
      const action = SexAction.lookup(code);
      const mainCategory = action.getMainCategory();
      const partCategory = action.getPartCategory();

      if ($mainCategories[mainCategory] == null) {
        $mainCategories[mainCategory] = {};
      }
      if ($partCategories[partCategory] == null) {
        $partCategories[partCategory] = {};
      }

      $mainCategories[mainCategory][action.getCode()] = action.getName();
      $partCategories[partCategory][action.getCode()] = action.getName();
    });

    console.log("=== Compiled Categories ===")
    console.log($mainCategories);
    console.log($partCategories);
  }

  function show() {
    const location = Location.lookup(GameState.getCurrentLocation());

    MainContent.setMainContent("views/training.html");
    MainContent.setBackground(location.getBackground());

    buildStatusPanel();
  }

  function buildStatusPanel() {
    // Name (Status Effects) (Relevant Stats)
    // [clothing]
    // [Stamina Bar] (2000/2000)
    // [Health Bar] (100/100)
    // -- PALAM ----- -------------- -------------- --------------
    // C Ples         V Ples         A Ples         B Ples        // Include pleasure ramps?
    // M Ples         Loyal          Desire         Submission
    // V Wet          A Wet          Shame          Learn         // These attributes are limited to the current scene and start at 0.
    // Pain           Fear           Hostile        Depression    // Which make sense to carry over. The whole convert to gems step is still mysterious.
    // Milk [7000/10000]
    // Sex[   ](0/2) Semen[XX  ](4/9) womb[X   ](3646p)       // Satasfaction Row [number of orgasms] []
    // In Use: [Clit Cap], [Nipple Cap]

    // My attributes:
    // [Control] slow changing, but training is used to increase it, so probably good to have.
    // [Affection/Fear/Respect] - Top level attributes to replace favor and service?
    // [Arousal/Pleasure] important to track. Can be on top rather than tracked on each part.

    // Pleasure bars would work better as a column of body parts.
    // Second column for training values, (loyal/obedience)/desire/submission/(shame/exposure)/(hostile/anger)/(depression/trauma)

    // Obedience / Desire / Submission (Built with light actions, kissing, carressing. More difficult actions possible as Obedience level increases.)
    //   desire => Lust Mark
    //
    // Shame / Anger / Suffering
    //   shame =>
    //   anger => Hate Mark (Hate marks raise all training thresholds. Results in orb/gem loss.)
    //   suffering(depression) = Pain Mark


    // The 'PALAM' bars overflow from the raw 'SOURCE' values generated by the actions.
    // The amount that overflows from the bars are what gets converted into JUEL (the gems)
    // Gems are spent on abilities.

    // Controller will need to maintain a training state, these training values are converted into the 'gems'

  }



  return Object.freeze({
    init,
    show,
  });

})();
